### ISSUE TITLE
local_interfaces

### ISSUE THREAD

**Issue by coreilly** [ULHPC/puppet-exim4#1]
I don't really understand but I was trying to integrate this module with one of my own and had a problem with the local_interfaces variable.

It's not in manifests/init.pp.  for some reason that caused me no end of trouble. Adding 
    $local_interfaces = $exim4::params::local_interfaces,
to manifests/init.pp made all my problems go away.

Again, I don't understand why or what was going on - without that I would keep getting "has no parameter named 'exim4::local_interfaces'"  

I tried using exim4::params::local_interfaces but that wouldn't work.  So I don't know but I figured I'd pass this along.

**Comment by hcartiaux** [comment]
I guess it's fixed.
